import React, { useState } from 'react';
import { User, Mail, Lock, Eye, EyeOff, AlertCircle, CheckCircle2, Sparkles, ArrowRight } from 'lucide-react';
import confetti from 'canvas-confetti';

export default function RegisterForm({ onSwitchToLogin, onSuccess }) {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: ''
  });

  const [errors, setErrors] = useState({});
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submittedData, setSubmittedData] = useState(null);

  // Calculate Password Strength
  const getPasswordStrength = (pwd) => {
    if (!pwd) return { score: 0, label: '', color: 'var(--border-color)' };
    let score = 0;
    if (pwd.length >= 8) score += 1;
    if (/[A-Z]/.test(pwd)) score += 1;
    if (/[0-9]/.test(pwd)) score += 1;
    if (/[^A-Za-z0-9]/.test(pwd)) score += 1;

    if (score <= 1) return { score: 1, label: 'Weak', color: 'var(--error)' };
    if (score === 2 || score === 3) return { score: 2, label: 'Medium', color: 'var(--warning)' };
    return { score: 3, label: 'Strong ✨', color: 'var(--success)' };
  };

  const strength = getPasswordStrength(formData.password);

  // Validate single field
  const validateField = (name, value) => {
    let error = '';
    if (name === 'name') {
      if (!value.trim()) {
        error = 'Full Name is required.';
      } else if (value.trim().length < 2) {
        error = 'Name must be at least 2 characters.';
      }
    }

    if (name === 'email') {
      if (!value.trim()) {
        error = 'Email address is required.';
      } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim())) {
        error = 'Please enter a valid email address (e.g. user@example.com).';
      }
    }

    if (name === 'password') {
      if (!value) {
        error = 'Password is required.';
      } else if (value.length < 6) {
        error = 'Password must be at least 6 characters long.';
      }
    }

    if (name === 'confirmPassword') {
      if (!value) {
        error = 'Please confirm your password.';
      } else if (value !== formData.password) {
        error = 'Passwords do not match.';
      }
    }

    setErrors((prev) => ({ ...prev, [name]: error }));
    return error;
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    validateField(name, value);

    // If changing password, revalidate confirmPassword if filled
    if (name === 'password' && formData.confirmPassword) {
      if (formData.confirmPassword !== value) {
        setErrors((prev) => ({ ...prev, confirmPassword: 'Passwords do not match.' }));
      } else {
        setErrors((prev) => ({ ...prev, confirmPassword: '' }));
      }
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    // Validate all fields
    const eName = validateField('name', formData.name);
    const eEmail = validateField('email', formData.email);
    const ePassword = validateField('password', formData.password);
    const eConfirm = validateField('confirmPassword', formData.confirmPassword);

    if (eName || eEmail || ePassword || eConfirm) {
      return;
    }

    setIsSubmitting(true);

    // Simulate registration process
    setTimeout(() => {
      setIsSubmitting(false);

      // Trigger Confetti!
      try {
        confetti({
          particleCount: 80,
          spread: 70,
          origin: { y: 0.6 }
        });
      } catch (err) {
        // Fallback silently if confetti library fails
      }

      const mockPayload = {
        name: formData.name.trim(),
        email: formData.email.trim().toLowerCase(),
        password: "[PROTECTED - BCrypt Hash will be generated by Spring Boot]",
        role: "ROLE_USER",
        created: new Date().toISOString()
      };

      setSubmittedData(mockPayload);
      if (onSuccess) {
        onSuccess(mockPayload);
      }
    }, 800);
  };

  return (
    <div className="auth-form-container">
      <form onSubmit={handleSubmit} className="auth-form" noValidate>
        {/* Full Name */}
        <div className={`form-group ${errors.name ? 'has-error' : ''}`}>
          <label className="form-label" htmlFor="register-name">
            Full Name
          </label>
          <div className="input-wrapper">
            <User className="input-icon" />
            <input
              id="register-name"
              type="text"
              name="name"
              className="form-input"
              placeholder="e.g. Alex Toymaker"
              value={formData.name}
              onChange={handleChange}
              autoComplete="name"
            />
          </div>
          {errors.name && (
            <div className="error-message">
              <AlertCircle size={14} />
              <span>{errors.name}</span>
            </div>
          )}
        </div>

        {/* Email Address */}
        <div className={`form-group ${errors.email ? 'has-error' : ''}`}>
          <label className="form-label" htmlFor="register-email">
            Email Address
          </label>
          <div className="input-wrapper">
            <Mail className="input-icon" />
            <input
              id="register-email"
              type="email"
              name="email"
              className="form-input"
              placeholder="alex@toyland.com"
              value={formData.email}
              onChange={handleChange}
              autoComplete="email"
            />
          </div>
          {errors.email && (
            <div className="error-message">
              <AlertCircle size={14} />
              <span>{errors.email}</span>
            </div>
          )}
        </div>

        {/* Password */}
        <div className={`form-group ${errors.password ? 'has-error' : ''}`}>
          <label className="form-label" htmlFor="register-password">
            Password
          </label>
          <div className="input-wrapper">
            <Lock className="input-icon" />
            <input
              id="register-password"
              type={showPassword ? 'text' : 'password'}
              name="password"
              className="form-input"
              placeholder="Min. 6 characters"
              value={formData.password}
              onChange={handleChange}
              autoComplete="new-password"
            />
            <button
              type="button"
              className="input-action-btn"
              onClick={() => setShowPassword(!showPassword)}
              title={showPassword ? 'Hide password' : 'Show password'}
              tabIndex={-1}
            >
              {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
            </button>
          </div>
          {errors.password ? (
            <div className="error-message">
              <AlertCircle size={14} />
              <span>{errors.password}</span>
            </div>
          ) : (
            formData.password.length > 0 && (
              <div className="password-meter">
                <div className="meter-bars">
                  <div
                    className="meter-bar"
                    style={{
                      background: strength.score >= 1 ? strength.color : 'var(--border-color)'
                    }}
                  />
                  <div
                    className="meter-bar"
                    style={{
                      background: strength.score >= 2 ? strength.color : 'var(--border-color)'
                    }}
                  />
                  <div
                    className="meter-bar"
                    style={{
                      background: strength.score >= 3 ? strength.color : 'var(--border-color)'
                    }}
                  />
                </div>
                <div className="meter-label">
                  <span>Strength</span>
                  <span style={{ color: strength.color }}>{strength.label}</span>
                </div>
              </div>
            )
          )}
        </div>

        {/* Confirm Password */}
        <div className={`form-group ${errors.confirmPassword ? 'has-error' : ''}`}>
          <label className="form-label" htmlFor="register-confirm-password">
            Confirm Password
          </label>
          <div className="input-wrapper">
            <Lock className="input-icon" />
            <input
              id="register-confirm-password"
              type={showConfirmPassword ? 'text' : 'password'}
              name="confirmPassword"
              className="form-input"
              placeholder="Re-enter your password"
              value={formData.confirmPassword}
              onChange={handleChange}
              autoComplete="new-password"
            />
            <button
              type="button"
              className="input-action-btn"
              onClick={() => setShowConfirmPassword(!showConfirmPassword)}
              title={showConfirmPassword ? 'Hide password' : 'Show password'}
              tabIndex={-1}
            >
              {showConfirmPassword ? <EyeOff size={18} /> : <Eye size={18} />}
            </button>
          </div>
          {errors.confirmPassword ? (
            <div className="error-message">
              <AlertCircle size={14} />
              <span>{errors.confirmPassword}</span>
            </div>
          ) : (
            formData.confirmPassword &&
            formData.confirmPassword === formData.password && (
              <div className="error-message" style={{ color: 'var(--success)' }}>
                <CheckCircle2 size={14} />
                <span>Passwords match perfectly!</span>
              </div>
            )
          )}
        </div>

        {/* Submit Register Button */}
        <button
          type="submit"
          className="btn btn-primary btn-full btn-lg"
          disabled={isSubmitting}
          style={{ marginTop: '0.5rem' }}
        >
          {isSubmitting ? (
            <span>Creating Toyland Account...</span>
          ) : (
            <>
              <span>Create Account</span>
              <ArrowRight size={18} />
            </>
          )}
        </button>
      </form>

      {/* Switch to Login Link */}
      <div className="form-footer-link">
        Already registered?
        <button type="button" onClick={onSwitchToLogin}>
          Sign In to your Account
        </button>
      </div>

      {/* Backend Payload Simulator */}
      {submittedData && (
        <div className="payload-card">
          <div className="payload-title">
            <span>Payload Ready for Spring Boot</span>
            <span className="payload-badge">POST /api/auth/register</span>
          </div>
          <pre>{JSON.stringify(submittedData, null, 2)}</pre>
        </div>
      )}
    </div>
  );
}
