# Server Configuration
server.port=${PORT:8080}


# Database Configuration - Aiven MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT Configuration
toyland.app.jwtSecret=${JWT_SECRET}
toyland.app.jwtExpirationMs=86400000


# Razorpay Test Mode Configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.shipping.fee=50.00